### ISSUE TITLE
Inverting PSU Sense

### ISSUE THREAD

**Issue by charredchar** [thagrol/fakewake#2]
First thank you so much for all of the work you have put into this. While researching how to power on and off a PC with a Pi (because WOL and Sleep is not reliable for me) I came across your posts multiple times.

But I have a slight issue. I am using relays and optocouplers for my input and outputs. Because of this I am getting a reversed input, where the pin is HIGH when the PC is off and LOW when the PC is on. I attempted a couple of times now to reverse this but I do not know enough to figure it out myself. Is there a simple way to change the code to make this work?

Thanks!

**Comment by thagrol** [comment]
I've not done any work on this for a while so the suggestion below is untested.

In line 758 try changing `pull_up=False to `pull_up=True` and replacing all occurances of `PSU_SENSE.value` in the script with `PSU_SENSE.is_active`

**Comment by charredchar** [comment]
I don't mind doing the testing for you.

It worked beautifully! Thank you! I figured it was something with PSU_Sense.value but as I said I don't know enough to know what I could change it to.
